### ISSUE TITLE
Tau Prolog might consider quoted(true) for Answer Substitutions

### ISSUE THREAD

**Issue by jburse** [jariazavalverde/tau-prolog#14]
Interesting how many details are involved in a Prolog Top-Level. For
example answer substitutions are usually displayed with writeq/1.

SWI-Prolog does it:

![40837960-68550e0c-659c-11e8-9d37-a60467f85da7](https://user-images.githubusercontent.com/5411487/40838090-f5c50134-659c-11e8-9695-263f9706d0aa.png)

**Comment by jburse** [comment]
Unfortunately I cannot pinpoint the ISO core standard here, since 
it doesn't say much about the Top-Level. This is more folklore. So far 
it seems not to work in Tau Prolog:

![40837948-5c1622d4-659c-11e8-87ec-7a29cd2e7296](https://user-images.githubusercontent.com/5411487/40838141-2c3d0dce-659d-11e8-85ef-753c3820e524.png)

**Comment by jariazavalverde** [comment]
We implement a `toString()` method for each Prolog object prototype (`Var`, `Num`, `Term`, `Substitution`, etc) as usual in JavaScript, since we don't have IO predicates yet.

The `toString()` method of terms is very *early* and doesn't have into account certain details (as quoted or graphic tokens). I'll update it after correcting parser's errors (#2 and #10).

**Comment by UWN** [comment]
There is a very simple rule of thumb for top levels: Answer substitutions should be precisely of the  form that they can be pasted back as a query.

**Comment by jariazavalverde** [comment]
Please, if you find any other misprinted atom, report it in this issue.
