### ISSUE TITLE
Does a Query also allow Comments?

### ISSUE THREAD

**Issue by jburse** [jariazavalverde/tau-prolog#15]
Sorry for disturbing again. But maybe you get more sponsoring with more
open issues. Always look on the bright side. I see Tau Prolog already supports
comments, as here:

![grafik](https://user-images.githubusercontent.com/5411487/40865812-a65dff5c-65fa-11e8-900f-7b3b5f204295.png)

**Comment by jburse** [comment]
But I am not sure whether comments are also supported in a query. This is
a little brain teaser with a comment in a query:

![grafik](https://user-images.githubusercontent.com/5411487/40865838-d0c18bc4-65fa-11e8-9746-83cec6280829.png)

And this is what is usually expected. Happy riddling:

![grafik](https://user-images.githubusercontent.com/5411487/40865843-db998fba-65fa-11e8-94d1-a3f195820be4.png)

**Comment by jariazavalverde** [comment]
I am testing the new parser and that problem is no longer there. If you found new errors in the parser, it would be better to wait until I update it (probably this week) before reporting them.

However, thanks for the notice!

![comments in goals](https://user-images.githubusercontent.com/5055295/40866157-761c6458-65fc-11e8-843e-e3035c66d101.png)
