### ISSUE TITLE
ISO core dynamic calls probably missing or with some problems

### ISSUE THREAD

**Issue by jburse** [jariazavalverde/tau-prolog#17]
A dynamic call is a variable in the body of a clause. Body conversion says
this variable should be wrapped into call/1, so that it can be correctly
executed without affecting the surrounding clause.

It seems that dynamic calls are probably missing in Tau Prolog, since
I get an empty response, neither "Yes" nor "No" answer. See this example
here that I just run:

![grafik](https://user-images.githubusercontent.com/5411487/40976326-1d1483fc-68ce-11e8-936d-39f78a401bbd.png)

**Comment by jburse** [comment]
This is the expected result, show what SWI-Prolog gives. Warning this is
quite a challenging result since you need clause consult under the hood right 
and you need call/1 implementation under the hood right.

So the expected result is twice a "Yes":

![grafik](https://user-images.githubusercontent.com/5411487/40976391-5480217a-68ce-11e8-9545-0e7eaaba085d.png)

**Comment by jariazavalverde** [comment]
When Tau Prolog doesn't return any substitution in the sandbox is because there is a JavaScript error. In general, the system allows dynamic calls (without replacing `X` by `call(X)`):

![dynamic call](https://user-images.githubusercontent.com/5055295/40992998-a085b010-68f8-11e8-9ad7-3746005dd213.png)

The problem is the cut. The `search` method is used to find the parent predicate that put the cut, and it is only defined for terms, so when it is applied to the variable `X`, Tau Prolog fails.

Thank you for the report!

**Comment by jburse** [comment]
Ok. Please note my other issue https://github.com/jariazavalverde/tau-prolog/issues/16
The ISO core standard allows naked dynamic call only when wrapped 
inside a call/1, which should be done by so called body conversion.

You might use naked dynamic call internally, where it is cut-transparent
etc.., for example this naked dynamic call would be very handy to
implement disjunction:
```
;(A, _) :- A.
;(_, A) :- A.
```
But the ISO core standard requires that such a feature is not anymore
available for the end-user, also not via assertz/1. See the afformentioned
other issue #16 which makes implementing the ISO core standard little

annoying. But most of the Prolog systems do that.

**Comment by jariazavalverde** [comment]
Ok, I'll reopen this problem, tagged as `iso conforming`, until I can review #16. Meanwhile, the error of the `search` method has been corrected.
