### ISSUE TITLE
No canonical syntax.

### ISSUE THREAD

**Issue by UWN** [jariazavalverde/tau-prolog#2]
All atoms that are both prefix and infix operators cannot be used as atoms. E.g. X = (-). is invalid syntax. Canonical syntax is here to ensure that a term can be read regardless of the operators present.

For you as developers the question you have to answer is: Do you prefer to design an experimental syntax with unkown disadvantages, as you currently do? Or do you rather stick to the existing ISO syntax? That has at least been used by many systems for 20+ years — with 40+ years behind in that style of syntax. You are referring to conformity tests for syntax, but you never used them. For one, writeq/1 is missing!

See [this](https://groups.google.com/d/msg/comp.lang.prolog/pCC_6IbcSB0/56A5M1fIDAAJ) and  [that](https://groups.google.com/d/msg/comp.lang.prolog/pCC_6IbcSB0/hZt7ZaLKDAAJ) for more specific situations.

**Comment by UWN** [comment]
Please note that this is a very serious bug! (The question is just an aside).

**Comment by UWN** [comment]
To illustrate how  much you are locked in: Consider I want to remove the infix operator `-`. The goal `op(0, yfx, -)` should do it. Well, it produces a syntax error. Same with `op(0,yfx,[-])` and the like ...

**Comment by jariazavalverde** [comment]
Yes, we are working on a [new parser](http://tau-prolog.org/files/doc/grammar-specification.pdf) implementation that will solve these problems. Note that we are still in beta and we've many things to add (e.g. I/O predicates) or improve/fix.

I'll leave this issue open until we incorporate the new version of the parser.

**Comment by UWN** [comment]
See it from a user's perspective: Is it worth to report non-conformance issues to Tau, if most of the time the response will be: we won't implement that.

**Comment by josegarciaclm95** [comment]
Hi @UWN 

Our goal is to implement our library conforming the standard. However, the application is still in **beta** and **lacks of any kind of funding**. We're aware of this deficiency you pointed out, and we'll address it as soon as we can.

**Comment by UWN** [comment]
@josegarciaclm95: OK, and what about the syntax?

**Comment by jburse** [comment]
How does the braket thing really work. The key is ISO 6.3.3.1,
it says what is an argument. And it has one special case
for arguments, namely:
                 
```
               arg = atom ;
Abstract: a       a
Condition: a is an Operator
```

I don't find such a production in the Tau Prolog Grammar. 
Thats why you get possibly an error:

```
?- X = (-).
error parsing query: error(syntax_error(line(1), column(7), found(')'), 
cause(unexpected token)))
```

You grammer only reads as follows, looking at arguments of an
compound term. Namely I see only the following production:

```
term2 --> lparen expr1400 term3
term3 --> comma expr1400 term3 | rparen
```
But the correct grammar, according to  ISO 6.3.3.1
would be as follows, namely:

```
term2 --> lparen term4 term3
term3 --> comma term4 term3 | rparen
term4 --> atom /* formerly operator */ | expr1400
```

**Comment by jburse** [comment]
Now how can this be implemented? Well there is a small trick
that other Prolog systems might also consider. At least this is how 
it is in Jekejeke Prolog done. We do not really pass around information

to let the system know when we are inside an argument or not.
I had an old prototype that did that, but it then turned out unnessary. 
We only assume we are inside an argument, when the argument is 

followed by comma or rparen.  That a comma or rparen follows term4, 
can be easily verifyed from the previous post here. And we apply this 
heuristic only to prevent a prefix operator lookup, more is not needed 

to get good results. So its basically this one line of code here:

```
                nextToken();
                /* ISO 6.3.3.1 */
                if (isTemplates(noTermTempls) || isTemplates(noOperTempls)) {
                    skel = help;
                } else {
                    Operator op = engine != null ? OperatorSearch.getOper(help,
                            Operator.TYPE_PREFIX, engine) : null;
```
https://github.com/jburse/jekejeke-devel/blob/master/jekrun/headless/jekpro/model/pretty/PrologReader.java#L352

**Comment by jburse** [comment]
Disclaimer: I only did a quick write up, of what I found
in my code, which is open source since a few days. Already
some time passed, that I have produced this solution.

Possibly the code might be more disputable, than the
fact that the ISO core standard has in its document
a section ISO 6.3.3.1 and corresponding productions,

which would be needed to capture the full grammar of
Prolog. The section 6.3.3.1 also gives the many examples
of operator overriding. Namely in this section we find

a footnote with:

NOTE - This concept of an “argument” ensures that both
the terms f(x,y) and f(:-, l [:-, :-I:-1) are
syntactically valid **whatever operators definitions**
are currently defined.

Please note the emphasis **whatever operators definitions**,
this does not yet completely clarify the issue here:
No canonical syntax - by UWN, 4 days ago
https://github.com/jariazavalverde/tau-prolog/issues/2

What is the missing piece. Well the missing piece
is that in a parented expression, the expression
itself is also an argument. So this Tau Prolog
production here for example:

`   expr0 --> lparen expr1400 rparen`

Needs to be also replaced by the same term4, the
term4 I already introduced for compound argumemts,
namely you'd better try to view it as:

```
   expr0 --> lparen term4 rparen
   term4 --> atom /* formerly operator */ | expr1400
```

This last missing piece is not explicit in the
standard in 6.3.4.1 Operand. But it can be guessed.
"arg" is only used in 6.3.5 list and in 6.3.3
compound terms.

Not sure whether the new version of the ISO
core standard has that fixed, or some Corrigendum
is doing this. But upon reflecting, a parented
expression is of course also an argument of some

sort, does also allow operator priority overriding,
as the comment there says.
