### ISSUE TITLE
Feature request: typescript typings

### ISSUE THREAD

**Issue by bgotink** [jariazavalverde/tau-prolog#79]
Typescript adds type information to javascript. By providing typescript typings, tau-prolog would make it a lot easier to be used in typescript projects and even in javascript projects as editors like Visual Studio Code use types to provide intellisense.

Would you be open to adding typings to the tau-prolog package?

I'd be willing to pick this up. I have already written partial types for a project I'm working on ([source](https://github.com/bgotink/package-constraints/blob/master/src/types/tau-prolog.d.ts)) as well as for https://github.com/yarnpkg/berry/pull/53#discussion_r271422658. These could be used as a basis to create full typings for the tau-prolog package.
Note that these types were created by reading the code, so parts of the file are probably wrong as I had to guess the types of some function arguments.

**Comment by josemariagarcia95** [comment]
At this moment, the tau-prolog package needs time to grow stable, and we still have work to do with the IO, so I'll close this issue for now, and maybe we'll attend it in the future.

**Comment by arcanis** [comment]
@josemariagarcia95 I'd just like to point out that using TS to author a library actually helps a *lot* with unstable packages, because consumers are notified of the changed APIs as soon as they update the package.

For instance we currently have handwritten types for tau-prolog, and I think because of this we didn't notice that an API changed, resulting in `thread.throwError is not a function` errors.
